name: AntiBot
main: somebody.is.madbro.AntiBot
version: 2.7.1-DEV
description: The ultimate spam protection for Minecraft.
softdepend: [AntiCheat]
commands:
   antibot:
    description: Usable Antibot Commands
    usage: |
      /<command> help - Help menu on the AntiBot system.
permissions:
  AntiBot.notify:
    default: false
    description: Notifies the player if there is a current invasion.
  AntiBot.join:
    default: false
    description: Allow users to bypass anti bot spam.
  AntiBot.voice:
    default: false
    description: Allow users to speak, even while voiced.
  AntiBot.chatspam:
    default: false
    description: Allows users to bypass anti chat spam.
  AntiBot.countryban:
    default: false
    description: Users with this permission can join the server if their home country is banned from the server.
  AntiBot.admin:
    default: false
    description: Basic Permissions to the Antibot system.
  AntiBot.admin.plus:
    default: false
    description: Gives full access to the system.
  AntiBot.admin.reload:
    default: false
    description: Ability to reload configuration.
  AntiBot.admin.info:
    default: false
    description: Check the status of AntiBot.
  AntiBot.admin.attack:
    default: false
    description: Turns on Invasion Mode manually.  Good if you know you're about to get attacked.
  AntiBot.admin.notify:
    default: false
    description: Gives extra details during invasions.  Tells this user if a system flush is needed.
  AntiBot.admin.flush:
    default: false
    description: Flush all connection throttling.  This could be on accident.
  AntiBot.admin.changeconf:
    default: false
    description: Change 2 configuration values ingame.  Amount of accounts and the time interval.
  AntiBot.admin.toggle:
    default: false
    description: Toggle AntiBot to be on or off.  Useful when getting legitimate players.